server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true

          routes:
            - id: product-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/products/**
              filters:
                - StripPrefix=1

            - id: user-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/users/**,/api/admin/**
              filters:
                - StripPrefix=1

            - id: cart-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/cart/items/**
              filters:
                - StripPrefix=1

            - id: order-service
              uri: http://localhost:8084
              predicates:
                - Path=/api/orders/**
              filters:
                - StripPrefix=1

            - id: product-openapi
              uri: http://localhost:8081
              predicates:
                - Path=/product/v3/api-docs
              filters:
                - RewritePath=/product/v3/api-docs,/v3/api-docs

            - id: user-openapi
              uri: http://localhost:8082
              predicates:
                - Path=/user/v3/api-docs
              filters:
                - RewritePath=/user/v3/api-docs,/v3/api-docs

            - id: cart-openapi
              uri: http://localhost:8083
              predicates:
                - Path=/cart/v3/api-docs
              filters:
                - RewritePath=/cart/v3/api-docs,/v3/api-docs

            - id: order-openapi
              uri: http://localhost:8084
              predicates:
                - Path=/order/v3/api-docs
              filters:
                - RewritePath=/order/v3/api-docs,/v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    use-root-path: true

    urls:
      - name: Product Service
        url: /product/v3/api-docs

      - name: User Service
        url: /user/v3/api-docs

      - name: Cart Service
        url: /cart/v3/api-docs

      - name: Order Service
        url: /order/v3/api-docs