spring:
  application:
    name: cart-service
  datasource:
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5432/cartdb
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true


resilience4j:
  circuitbreaker:
    instances:
      productClient:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

  timelimiter:
    instances:

      productClient:
        timeout-duration: 3s

  retry:
    instances:
      cartClient:
        max-attempts: 3
        wait-duration: 500ms

springdoc:
  api-docs:
    enabled: true

  swagger-ui:
    enabled: true

server:
  port: 8083